cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: lukas.richter@hpe.com 
      logged_in: false
      name: Admin
      password: $2b$12$AAREG9bxznBaRPSb9x9.OO0yPQ6qno5k/gTsSVqQC6/FD/BzeAjRa