cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: example@hpe.com
      logged_in: false
      name: Admin                                                                   # Nutzernamen einfügen
      password:                                                                     # Passworthash einfügen
