cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: lukas.richter@hpe.com 
      logged_in: false
      name: Admin
      password: $2b$12$8SHjXqlkJC2Z.2pHjsrSm.vrQ/ml1k8x9la/wCRhVPOfVfKkwDpQi